apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-scaller
spec:
 scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: hpa-web-dep
 minReplicas: 2
 maxReplicas: 10
 metrics:
 - type: Resource
   resource:
    name: cpu
    target:
     type: Utilization
     averageUtilization: 10
