apiVersion: v1
kind: Pod
metadata:
 name: liveness-readiness-pod
 namespace: dev-environment
spec:
 containers:
 - name: liveness-readiness-pod-container
   image: nginx:latest
   resources:
    limits:
     cpu: "100m"
     memory: "200Mi"
   livenessProbe:
    httpGet:
     path: /healthz
     port: 80
    initialDelaySeconds: 3
    periodSeconds: 3
   readinessProbe:
    httpGet:
     path: /healthz
     port: 80
    initialDelaySeconds: 3
    periodSeconds: 3
