apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: log-collector
 namespace: dev-environment
spec:
 selector:
  matchLabels:
   app: log-collector
 template:
  metadata:
   labels:
    app: log-collector
  spec:
   containers:
   - name: logapp
     image: fluentd
