apiVersion: v1
kind: Pod
metadata:
 name: readiness-pod
 namespace: dev-environment
spec:
 containers:
 - name: readiness-container
   image: nginx
   readinessProbe:
    httpGet:
     path: /healthz
     port: 80
    initialDelaySeconds: 3
    periodSeconds: 3
