apiVersion: apps/v1
kind: Deployment
metadata:
 name: hpa-web-dep
 namespace: dev-environment
spec:
 replicas: 2
 selector:
  matchLabels:
   app: scalable
 template:
  metadata:
   labels:
    app: scalable
  spec:
   containers:
   - name: scalable
     image: nginx
     resources:
      requests:
       cpu: "100m"
       memory: "250Mi"
      limits:
       cpu: "200m"
       memory: "300Mi"

