apiVersion: batch/v1
kind: CronJob
metadata:
 name: batch-job
 labels:
  app: job
spec:
 schedule: "* * * * *"
 jobTemplate:
  spec:
   template:
    spec:
     containers:
     - name: jobcontainer
       image: busybox
       args:
       - /bin/sh
       - -c
       - date; echo Hello Kubernetes
     restartPolicy: OnFailure
  
