apiVersion: v1
kind: Pod
metadata:
 name: resource-limits-pod
 labels:
  app: web
spec:
 containers:
 - name: web
   image: nginx:latest
   resources:
    limits:
     memory: "256Mi"
     cpu: "500m"
