apiVersion: v1
kind: Pod
metadata:
 name: configmap-pod
spec:
 containers:
  - name: app
    image: nginx
    env:
     - name: APP_ENV
       valueFrom:
        configMapKeyRef:
         name: app-config
         key: APP_ENV
    resources:
     limits:
      memory: "250Mi"
      cpu: "250m"
