apiVersion: v1
kind: Pod
metadata:
 name: demo-pod
spec:
 containers:
 - name: ng
   image: nginx
   resources:
    limits:
     memory: "250Mi"
     cpu: "250m"
   volumeMounts:
   - mountPath: /data
     name: pv-data
 volumes:
 - name: pv-data
   persistentVolumeClaim:
    claimName: pvc-data
