apiVersion: v1
kind: Pod
metadata:
 name: secret-pod
spec:
 containers:
  - name: nginx
    image: nginx
    env:
     - name: DB_USER
       valueFrom:
	secretKeyRef:
	 name: db-secret
	 key: DB_USER
     - name: DB_PASS
       valueFrom:
        secretKeyRef:
         name: db-secret
         key: DB_PASS
     resources:     
      limits:
       memory: "250Mi"
       cpu: "250m" 
