apiVersion: v1
kind: Pod
metadata:
 name: secret-pod
spec:
 containers:
 - name: ng
   image: nginx
   env:
   - name: DB_USER
     valueFrom:
      secretKeyRef:
       name: db-secret
       key: username
   - name: DB_PASS
     valueFrom:
      secretKeyRef:
       name: db-secret
       key: password
   resources:
    limits:
     memory: "250Mi"
     cpu: "250m"
   
